spring.application.name=personalexpense

spring.jackson.date-format="yyyy-MM-dd"

otel.exporter.otlp.endpoint=http://localhost:4317
otel.exporter.otlp.protocol=grpc
otel.traces.sampler=always_on
otel.propagators=tracecontext,baggage

aws.region=us-east-1
aws.bucket_name=fintracker-receipts

spring.devtools.restart.enabled=false
spring.devtools.livereload.enabled=true


