kind: Deployment
apiVersion: apps/v1
metadata:
  name: userauthenticationdeployment
  namespace: fintracker
  labels:
    env: prod
    type: userauthentication
spec:
  replicas: 1
  selector:
    matchLabels:
      type: userauthenticationpod
  template:
    metadata:
      labels:
        type: userauthenticationpod
    spec:
      containers:
        - name: userauthenticationimage
          image: us-central1-docker.pkg.dev/fintracker-466022/fintracker/userauthentication/userauthentication:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_URL
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: REDIS_URL
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials

                  key: REDIS_PASSWORD

