apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: fintracker
type: Opaque
stringData:
  DB_URL: "jdbc:postgresql://10.17.80.3:5432/fintrackerdb"
  DB_USERNAME: "postgres"
  DB_PASSWORD: "\g_J,#`DreXp%y`y"
