kind: Deployment
apiVersion: apps/v1
metadata:
  name: gatewayService
  labels:
    env: prod
    type: gateway
spec:
  replicas: 1
  template:
    metadata:
      labels:
        type: gatewaypod
    spec:
      - containers:
          - name: gatewayimage
            image: us-central1-docker.pkg.dev/fintracker-466022/fintracker/gateway/fintrackergateway:latest
            ports:
              - containerPort: 8080
  selector:
    matchLabels:
      type: gatewaypod