apiVersion: "v1"
kind: "Service"
metadata:
  name: "fintracker.vrajpatelproject.software"
  namespace: fintracker
  labels:
    env: "prod"
    type: "gateway"
spec:
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  selector:
    type: "gatewaypod"

