apiVersion: "v1"
kind: "Service"
metadata:
  name: "gatewaydeployment-service"
  namespace: fintracker
  labels:
    env: "prod"
    type: "gateway"
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "gateway-backend-config"}'
spec:
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  selector:
    type: "gatewaypod"

