apiVersion: "v1"
kind: "Service"
metadata:
  name: "gatewaydeployment-service"
  namespace: "default"
  labels:
    env: "prod"
    type: "gateway"
spec:
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  selector:
    type: "gatewaypod"
  type: "NodePort"
