# Disable Eureka if not needed
eureka.client.enabled=false

# Enable logging
logging.level.org.vrajpatel.fintrackergateway=debug
logging.level.org.vrajpatel.fintrackergateway.Config.AuthConfigGatewayFilter=debug


#domain=vrajpatelproject.software

# Set validation URL (no quotes!)
validationUrl=http://userauthenticationservice:8080/userauth/api/auth

# Enable health endpoint



# CORS configuration
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=https://frontend.vrajpatelproject.software
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].exposedHeaders[0]=Authorization
spring.cloud.gateway.globalcors.corsConfigurations.[/**].exposedHeaders[1]=Set-Cookie
spring.cloud.gateway.globalcors.corsConfigurations.[/**].maxAge=3600
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowCredentials=true

# Static service discovery for local development
spring.cloud.discovery.client.simple.instances.userauthenticationservice[0].uri=http://userauthenticationservice:8080



#Circuit Breaker
resilience4j.circuitbreaker.instances.CircuitBreaker.register-health-indicator=true
resilience4j.circuitbreaker.instances.CircuitBreaker.sliding-window-size=10
resilience4j.circuitbreaker.instances.CircuitBreaker.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.CircuitBreaker.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.CircuitBreaker.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.CircuitBreaker.minimum-number-of-calls=5
