server.port=8081

eureka.client.enabled=false

#eureka.client.service-url.defaultZone=${SERVICE_URL}
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true

logging.level.root=debug
logging.level.org.vrajpatel.fintrackergateway=debug
logging.level.org.vrajpatel.fintrackergateway.Config.AuthConfigGatewayFilter=debug



spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedOrigins=https://localhost:5173
spring.cloud.gateway.server.webflux.globalcors.corsConfigurations.[/**].allowedMethods=*
spring.cloud.gateway.server.webflux.globalcors.corsConfigurations.[/**].allowedHeaders=*
spring.cloud.gateway.server.webflux.globalcors.corsConfigurations.[/**].exposedHeaders[0]=Authorization
spring.cloud.gateway.server.webflux.globalcors.corsConfigurations.[/**].maxAge=3600
spring.cloud.gateway.server.webflux.globalcors.corsConfigurations.[/**].allowCredentials=true
spring.cloud.gateway.server.webflux.globalcors.corsConfigurations.[/**].exposedHeaders[1]=Set-Cookie

resilience4j.circuitbreaker.instances.CircuitBreaker.register-health-indicator=true
resilience4j.circuitbreaker.instances.CircuitBreaker.sliding-window-size=10
resilience4j.circuitbreaker.instances.CircuitBreaker.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.CircuitBreaker.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.CircuitBreaker.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.CircuitBreaker.minimum-number-of-calls=5

# OAUTH Routes
