apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: fintracker
type: Opaque
stringData:
  DB_URL: "jdbc:postgresql://10.10.0.4:5432/fintracker"
  DB_USERNAME: "postgres"
  DB_PASSWORD: "Fintracker@12"