eureka.client.enabled = false

authorizedUrl=https://fintracker.vrajpatelproject.software

logging.level.root=error
logging.level.org.vrajpatel.userauthservice=error
logging.level.org.vrajpatel.userauthservice.utils.JwtUtils.TokenAuthenticationFilter=error
logging.level.org.vrajpatel.userauthservice.config.SecurityConfig=error


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate

spring.datasource.hikari.maximum-pool-size=50
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.connection-timeout=3000

server.tomcat.threads.max=400
server.tomcat.threads.min-spare=20
server.tomcat.accept-count=100


spring.data.redis.host=${REDIS_URL}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.port=6379

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vp14.dev@gmail.com
spring.mail.password=${MAIL_PASSWORD}
logging.level.org.springframework.boot.autoconfigure.mail=error
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2


spring.security.oauth2.client.registration.google.client-id=134868651465-grbhf79u3qogn36lda1pv59dvaqktf0j.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=https://fintracker.vrajpatelproject.software/oauth2/callback/google

spring.security.oauth2.client.registration.github.client-id=Ov23li68JK6djQN7ja3i
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.redirect-uri=https://fintracker.vrajpatelproject.software/oauth2/callback/github
spring.security.oauth2.client.registration.github.scope=user:email,read:user

spring.security.oauth2.client.registration.facebook.client-id=1027198535829065
spring.security.oauth2.client.registration.facebook.client-secret=${FACEBOOK_CLIENT_SECRET}
spring.security.oauth2.client.registration.facebook.redirect-uri=https://fintracker.vrajpatelproject.software/oauth2/callback/facebook
spring.security.oauth2.client.registration.facebook.scope=email,public_profile

spring.security.oauth2.client.provider.facebook.authorizationUri=https://www.facebook.com/v16.0/dialog/oauth
spring.security.oauth2.client.provider.facebook.tokenUri=https://graph.facebook.com/v16.0/oauth/access_token
spring.security.oauth2.client.provider.facebook.userInfoUri=https://graph.facebook.com/v3.0/me?fields=id,email,first_name,middle_name,last_name,name,verified,picture.width(250).height(250)

domain=vrajpatelproject.software

app.oauth2.authorized-redirect-uris=https://frontend.vrajpatelproject.software/oauth2/redirect


otel.exporter.otlp.endpoint=http://jaeger:4317
otel.exporter.otlp.protocol=grpc
otel.traces.sampler=always_on
otel.propagators=tracecontext,baggage

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=never
management.endpoint.prometheus.access=unrestricted